### ISSUE TITLE
A typo in the setup instruction 

### ISSUE THREAD

**Issue by mcyc** [ArianaBakhtyari/specMC#1]
The following instruction should be `pip install setup.py` instead.
https://github.com/ArianaBakhtyari/specMC/blob/1b0cd3b5767d9d9ab5f952c26c5d243ece6451ba/README.md?plain=1#L5

**Comment by ArianaBakhtyari** [comment]
oh i aactually think it's supposed to be python3 setup.py install. because that's what I did. not pip.
