### ISSUE TITLE
SpectralModel initiated from the wrong class 

### ISSUE THREAD

**Issue by mcyc** [ArianaBakhtyari/specMC#3]
The SpectralModel object obtained below is initiated from `pyspeckit`'s SpectralModel class instead of the one from this package's `model_withPriors.py`.
https://github.com/ArianaBakhtyari/specMC/blob/1b0cd3b5767d9d9ab5f952c26c5d243ece6451ba/specMC/SpecModel.py#L241

**Comment by mcyc** [comment]
We are currently working on a solution under the `mc_fixes` branch.

**Comment by ArianaBakhtyari** [comment]
sound good! Thank you!
